on: push
jobs:
  checkout_immortal_Repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: hanwckf/immortalwrt-mt798x
      - run: pwd
      - name: show system infomation
        run: |-
          lscpu
          free -m
      - name: show all file
        run: ls
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/toolchain/Makefile
          asset_name: mything
          tag: ${{ github.ref }}
          overwrite: true
          body: This is my release text
